{% set results = get_column_values_from_query("select * from " ~ var('V_DB') ~ "." ~ var('V_Entity_Schema')~ "." ~ var('V_Mkt')~" where DATASOURCE_TYPE = 'FB_ADS' and READY_TO_PROCESS = 'TRUE'", "ENTITY_DATASORUCE_NAME||'#'||DATASOURCE_TYPE")%}

{% if not var("ad_reporting__facebook_ads_enabled") %}
{{
    config(
        enabled=false
    )
}}
{% endif %}

{% for V_SF_Schema in results %}

{% if V_SF_Schema != 'X' %} 
{% set schema_nm,entity_typ = V_SF_Schema.split('#') %}
{% else %}
{% set entity_typ = 'X' %}
{% endif %}

 {% if  entity_typ == 'FB_ADS'  %} 
      
  select
        {{ dbt_utils.surrogate_key('_FIVETRAN_ID') }}  AS ACC_HIS_ID,
        AGENCY_CLIENT_DECLARATION_CLIENT_POSTAL_CODE,
AMOUNT_SPENT,
CREATED_TIME,
AGENCY_CLIENT_DECLARATION_CLIENT_COUNTRY_CODE,
BUSINESS_STATE,
_FIVETRAN_ID,
END_ADVERTISER,
MEDIA_AGENCY,
IO_NUMBER,
OWNER,
BUSINESS_CITY,
BUSINESS_COUNTRY_CODE,
BUSINESS_STREET_2,
MIN_DAILY_BUDGET,
ACCOUNT_STATUS,
IS_ATTRIBUTION_SPEC_SYSTEM_DEFAULT,
MIN_CAMPAIGN_GROUP_SPEND_CAP,
OFFSITE_PIXELS_TOS_ACCEPTED,
TIMEZONE_NAME,
AGE,
IS_PERSONAL,
AGENCY_CLIENT_DECLARATION_HAS_WRITTEN_MANDATE_FROM_ADVERTISER,
BUSINESS_MANAGER_PRIMARY_PAGE,
HAS_MIGRATED_PERMISSIONS,
CURRENCY,
AGENCY_CLIENT_DECLARATION_AGENCY_REPRESENTING_CLIENT,
AGENCY_CLIENT_DECLARATION_CLIENT_EMAIL_ADDRESS,
BUSINESS_MANAGER_UPDATED_BY,
IS_NOTIFICATIONS_ENABLED,
DISABLE_REASON,
TAX_ID,
AGENCY_CLIENT_DECLARATION_CLIENT_CITY,
AGENCY_CLIENT_DECLARATION_CLIENT_NAME,
AGENCY_CLIENT_DECLARATION_IS_CLIENT_PAYING_INVOICES,
IS_DIRECT_DEALS_ENABLED,
BUSINESS_MANAGER_UPDATE_TIME,
END_ADVERTISER_NAME,
IS_PREPAY_ACCOUNT,
BUSINESS_ZIP,
BALANCE,
BUSINESS_MANAGER_TIMEZONE_ID,
NAME,
IS_TAX_ID_REQUIRED,
AGENCY_CLIENT_DECLARATION_CLIENT_BASED_IN_FRANCE,
TAX_ID_STATUS,
SALESFORCE_INVOICE_GROUP_ID,
TAX_ID_TYPE,
ID,
SPEND_CAP,
BUSINESS_NAME,
AGENCY_CLIENT_DECLARATION_CLIENT_STREET_2,
AGENCY_CLIENT_DECLARATION_CLIENT_PROVINCE,
BUSINESS_MANAGER_MANAGER_ID,
BUSINESS_MANAGER_CREATED_TIME,
AGENCY_CLIENT_DECLARATION_CLIENT_STREET,
TIMEZONE_OFFSET_HOURS_UTC,
BUSINESS_STREET,
CAN_CREATE_BRAND_LIFT_STUDY,
BUSINESS_MANAGER_CREATED_BY,
TIMEZONE_ID,
NEXT_BILL_DATE,
CAPABILITIES,
PARTNER,
BUSINESS_MANAGER_NAME,
_FIVETRAN_SYNCED,
        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM {{ schema_nm }}.ACCOUNT_HISTORY
          {% if not loop.last %}
            UNION ALL
        {% endif %} 
        {% elif  entity_typ == 'X'  %} 
         select
       NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_POSTAL_CODE,
NULL AS AMOUNT_SPENT,
NULL AS CREATED_TIME,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_COUNTRY_CODE,
NULL AS BUSINESS_STATE,
NULL AS _FIVETRAN_ID,
NULL AS END_ADVERTISER,
NULL AS MEDIA_AGENCY,
NULL AS IO_NUMBER,
NULL AS OWNER,
NULL AS BUSINESS_CITY,
NULL AS BUSINESS_COUNTRY_CODE,
NULL AS BUSINESS_STREET_2,
NULL AS MIN_DAILY_BUDGET,
NULL AS ACCOUNT_STATUS,
NULL AS IS_ATTRIBUTION_SPEC_SYSTEM_DEFAULT,
NULL AS MIN_CAMPAIGN_GROUP_SPEND_CAP,
NULL AS OFFSITE_PIXELS_TOS_ACCEPTED,
NULL AS TIMEZONE_NAME,
NULL AS AGE,
NULL AS IS_PERSONAL,
NULL AS AGENCY_CLIENT_DECLARATION_HAS_WRITTEN_MANDATE_FROM_ADVERTISER,
NULL AS BUSINESS_MANAGER_PRIMARY_PAGE,
NULL AS HAS_MIGRATED_PERMISSIONS,
NULL AS CURRENCY,
NULL AS AGENCY_CLIENT_DECLARATION_AGENCY_REPRESENTING_CLIENT,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_EMAIL_ADDRESS,
NULL AS BUSINESS_MANAGER_UPDATED_BY,
NULL AS IS_NOTIFICATIONS_ENABLED,
NULL AS DISABLE_REASON,
NULL AS TAX_ID,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_CITY,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_NAME,
NULL AS AGENCY_CLIENT_DECLARATION_IS_CLIENT_PAYING_INVOICES,
NULL AS IS_DIRECT_DEALS_ENABLED,
NULL AS BUSINESS_MANAGER_UPDATE_TIME,
NULL AS END_ADVERTISER_NAME,
NULL AS IS_PREPAY_ACCOUNT,
NULL AS BUSINESS_ZIP,
NULL AS BALANCE,
NULL AS BUSINESS_MANAGER_TIMEZONE_ID,
NULL AS NAME,
NULL AS IS_TAX_ID_REQUIRED,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_BASED_IN_FRANCE,
NULL AS TAX_ID_STATUS,
NULL AS SALESFORCE_INVOICE_GROUP_ID,
NULL AS TAX_ID_TYPE,
NULL AS ID,
NULL AS SPEND_CAP,
NULL AS BUSINESS_NAME,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_STREET_2,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_PROVINCE,
NULL AS BUSINESS_MANAGER_MANAGER_ID,
NULL AS BUSINESS_MANAGER_CREATED_TIME,
NULL AS AGENCY_CLIENT_DECLARATION_CLIENT_STREET,
NULL AS TIMEZONE_OFFSET_HOURS_UTC,
NULL AS BUSINESS_STREET,
NULL AS CAN_CREATE_BRAND_LIFT_STUDY,
NULL AS BUSINESS_MANAGER_CREATED_BY,
NULL AS TIMEZONE_ID,
NULL AS NEXT_BILL_DATE,
NULL AS CAPABILITIES,
NULL AS PARTNER,
NULL AS BUSINESS_MANAGER_NAME,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM dual     

    {% endif %}
{% endfor %}