{% set results = get_column_values_from_query("select * from " ~ var('V_DB') ~ "." ~ var('V_Entity_Schema')~ "." ~ var('V_Mkt')~" where DATASOURCE_TYPE = 'FB_ADS' and READY_TO_PROCESS = 'TRUE'", "ENTITY_DATASORUCE_NAME||'#'||DATASOURCE_TYPE")%}

{% if not var("enable_SF_source") %}
{{
    config(
        enabled=false
    )
}}
{% endif %}

{% for V_SF_Schema in results %}


{% if V_SF_Schema != 'X' %} 
{% set schema_nm,entity_typ = V_SF_Schema.split('#') %}
{% else %}
{% set entity_typ = 'X' %}
{% endif %}

 {% if  entity_typ == 'FB_ADS'  %} 
      
  select
        {{ dbt_utils.surrogate_key('ID') }}  AS ADS_ID,
        PROMOTED_OBJECT_PRODUCT_SET_ID,
TARGETING_EXCLUDED_CONNECTIONS,
PROMOTED_OBJECT_OBJECT_STORE_URL,
TARGETING_USER_DEVICE,
OPTIMIZATION_GOAL,
TARGETING_EXCLUDED_PUBLISHER_CATEGORIES,
TARGETING_PUBLISHER_PLATFORMS,
BILLING_EVENT,
LIFETIME_BUDGET,
TARGETING_GEO_LOCATIONS_COUNTRIES,
PROMOTED_OBJECT_PIXEL_ID,
CREATED_TIME,
BID_STRATEGY,
TARGETING_FLEXIBLE_SPEC,
TARGETING_USER_ADCLUSTERS,
NAME as ad_set_name,
TARGETING_WIRELESS_CARRIER,
LIFETIME_IMPS,
TARGETING_EDUCATION_STATUSES,
TARGETING_FRIENDS_OF_CONNECTIONS,
TARGETING_WORK_EMPLOYERS,
EFFECTIVE_STATUS,
BID_INFO_ACTIONS,
TARGETING_AUDIENCE_NETWORK_POSITIONS,
RF_PREDICTION_ID,
TARGETING_EDUCATION_MAJORS,
ID as ad_set_id,
PROMOTED_OBJECT_OFFER_ID,
START_TIME,
USE_NEW_APP_CLICK,
BUDGET_REMAINING,
PROMOTED_OBJECT_EVENT_ID,
PROMOTED_OBJECT_PLACE_PAGE_SET_ID,
RECURRING_BUDGET_SEMANTICS,
UPDATED_TIME,
TARGETING_EXCLUDED_USER_DEVICE,
TARGETING_LOCALES,
TARGETING_AGE_MAX,
BID_AMOUNT,
TARGETING_EDUCATION_SCHOOLS,
TARGETING_EXCLUDED_PUBLISHER_LIST_IDS,
TARGETING_COLLEGE_YEARS,
INSTAGRAM_ACTOR_ID,
TARGETING_AGE_MIN,
TARGETING_USER_OS,
ACCOUNT_ID,
CONFIGURED_STATUS,
DAILY_BUDGET,
PROMOTED_OBJECT_APPLICATION_ID,
END_TIME,
PROMOTED_OBJECT_PAGE_ID,
CAMPAIGN_ID,
TARGETING_FACEBOOK_POSITIONS,
TARGETING_EFFECTIVE_AUDIENCE_NETWORK_POSITIONS,
TARGETING_GEO_LOCATIONS_LOCATION_TYPES,
STATUS,
ADSET_SOURCE_ID,
PROMOTED_OBJECT_CUSTOM_EVENT_TYPE,
TARGETING_CONNECTIONS,
TARGETING_WORK_POSITIONS,
TARGETING_APP_INSTALL_STATE,
DESTINATION_TYPE,
TARGETING_INSTAGRAM_POSITIONS,
TARGETING_EXCLUSIONS,
PROMOTED_OBJECT_PRODUCT_CATALOG_ID,
TARGETING_DEVICE_PLATFORMS,
_FIVETRAN_SYNCED,
        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM {{ schema_nm }}.AD_SET_HISTORY
          {% if not loop.last %}
            UNION ALL
        {% endif %} 
        {% elif  entity_typ == 'X'  %} 
         select
        NULL AS PROMOTED_OBJECT_PRODUCT_SET_ID,
NULL AS TARGETING_EXCLUDED_CONNECTIONS,
NULL AS PROMOTED_OBJECT_OBJECT_STORE_URL,
NULL AS TARGETING_USER_DEVICE,
NULL AS OPTIMIZATION_GOAL,
NULL AS TARGETING_EXCLUDED_PUBLISHER_CATEGORIES,
NULL AS TARGETING_PUBLISHER_PLATFORMS,
NULL AS BILLING_EVENT,
NULL AS LIFETIME_BUDGET,
NULL AS TARGETING_GEO_LOCATIONS_COUNTRIES,
NULL AS PROMOTED_OBJECT_PIXEL_ID,
NULL AS CREATED_TIME,
NULL AS BID_STRATEGY,
NULL AS TARGETING_FLEXIBLE_SPEC,
NULL AS TARGETING_USER_ADCLUSTERS,
NULL AS ad_set_name,
NULL AS TARGETING_WIRELESS_CARRIER,
NULL AS LIFETIME_IMPS,
NULL AS TARGETING_EDUCATION_STATUSES,
NULL AS TARGETING_FRIENDS_OF_CONNECTIONS,
NULL AS TARGETING_WORK_EMPLOYERS,
NULL AS EFFECTIVE_STATUS,
NULL AS BID_INFO_ACTIONS,
NULL AS TARGETING_AUDIENCE_NETWORK_POSITIONS,
NULL AS RF_PREDICTION_ID,
NULL AS TARGETING_EDUCATION_MAJORS,
NULL AS ad_set_id,
NULL AS PROMOTED_OBJECT_OFFER_ID,
NULL AS START_TIME,
NULL AS USE_NEW_APP_CLICK,
NULL AS BUDGET_REMAINING,
NULL AS PROMOTED_OBJECT_EVENT_ID,
NULL AS PROMOTED_OBJECT_PLACE_PAGE_SET_ID,
NULL AS RECURRING_BUDGET_SEMANTICS,
NULL AS UPDATED_TIME,
NULL AS TARGETING_EXCLUDED_USER_DEVICE,
NULL AS TARGETING_LOCALES,
NULL AS TARGETING_AGE_MAX,
NULL AS BID_AMOUNT,
NULL AS TARGETING_EDUCATION_SCHOOLS,
NULL AS TARGETING_EXCLUDED_PUBLISHER_LIST_IDS,
NULL AS TARGETING_COLLEGE_YEARS,
NULL AS INSTAGRAM_ACTOR_ID,
NULL AS TARGETING_AGE_MIN,
NULL AS TARGETING_USER_OS,
NULL AS ACCOUNT_ID,
NULL AS CONFIGURED_STATUS,
NULL AS DAILY_BUDGET,
NULL AS PROMOTED_OBJECT_APPLICATION_ID,
NULL AS END_TIME,
NULL AS PROMOTED_OBJECT_PAGE_ID,
NULL AS CAMPAIGN_ID,
NULL AS TARGETING_FACEBOOK_POSITIONS,
NULL AS TARGETING_EFFECTIVE_AUDIENCE_NETWORK_POSITIONS,
NULL AS TARGETING_GEO_LOCATIONS_LOCATION_TYPES,
NULL AS STATUS,
NULL AS ADSET_SOURCE_ID,
NULL AS PROMOTED_OBJECT_CUSTOM_EVENT_TYPE,
NULL AS TARGETING_CONNECTIONS,
NULL AS TARGETING_WORK_POSITIONS,
NULL AS TARGETING_APP_INSTALL_STATE,
NULL AS DESTINATION_TYPE,
NULL AS TARGETING_INSTAGRAM_POSITIONS,
NULL AS TARGETING_EXCLUSIONS,
NULL AS PROMOTED_OBJECT_PRODUCT_CATALOG_ID,
NULL AS TARGETING_DEVICE_PLATFORMS,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM dual     

    {% endif %}
{% endfor %}