{% set results = get_column_values_from_query("select * from " ~ var('V_DB') ~ "." ~ var('V_Entity_Schema')~ "." ~ var('V_Mkt')~" where DATASOURCE_TYPE = 'FB_ADS' and READY_TO_PROCESS = 'TRUE'", "ENTITY_DATASORUCE_NAME||'#'||DATASOURCE_TYPE")%}

{% if not var("enable_SF_source") %}
{{
    config(
        enabled=false
    )
}}
{% endif %}

{% for V_SF_Schema in results %}


{% if V_SF_Schema != 'X' %} 
{% set schema_nm,entity_typ = V_SF_Schema.split('#') %}
{% else %}
{% set entity_typ = 'X' %}
{% endif %}

 {% if  entity_typ == 'FB_ADS'  %} 
      
  select
        {{ dbt_utils.surrogate_key('ID') }}  AS CRE_ID,
        OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_IOS,
ID as CREATIVE_ID,
OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_IPAD,
OBJECT_STORY_LINK_DATA_DESCRIPTION,
TEMPLATE_APP_LINK_SPEC_IOS,
TITLE,
TEMPLATE_LINK,
VIDEO_CALL_TO_ACTION_VALUE_LINK,
ACTOR_ID,
OBJECT_STORY_LINK_DATA_CAPTION,
OBJECT_URL,
_FIVETRAN_ID,
EFFECTIVE_INSTAGRAM_STORY_ID,
PAGE_MESSAGE,
CAROUSEL_AD_LINK,
ASSET_FEED_SPEC_LINK_URLS,
OBJECT_STORY_ID,
CALL_TO_ACTION_TYPE,
USE_PAGE_ACTOR_OVERRIDE,
IMAGE_URL,
INSTAGRAM_PERMALINK_URL,
NAME as CREATIVE_NAME,
TEMPLATE_CHILD_ATTACHMENTS,
PAGE_LINK,
TEMPLATE_MESSAGE,
TEMPLATE_APP_LINK_SPEC_IPHONE,
TEMPLATE_PAGE_LINK,
OBJECT_STORY_LINK_DATA_LINK,
OBJECT_ID,
TEMPLATE_APP_LINK_SPEC_ANDROID,
OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_ANDROID,
EFFECTIVE_OBJECT_STORY_ID,
PRODUCT_SET_ID,
IMAGE_FILE,
BODY,
OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_IPHONE,
STATUS,
OBJECT_STORY_LINK_DATA_MESSAGE,
THUMBNAIL_URL,
TEMPLATE_DESCRIPTION,
VIDEO_ID,
INSTAGRAM_STORY_ID,
OBJECT_TYPE,
LINK_OG_ID,
BRANDED_CONTENT_SPONSOR_PAGE_ID,
TEMPLATE_CAPTION,
TEMPLATE_URL,
ACCOUNT_ID,
IMAGE_HASH,
LINK_URL,
APPLINK_TREATMENT,
TEMPLATE_APP_LINK_SPEC_IPAD,
INSTAGRAM_ACTOR_ID,
OBJECT_STORY_LINK_DATA_CHILD_ATTACHMENTS,
URL_TAGS,
_FIVETRAN_SYNCED,
        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM {{ schema_nm }}.CREATIVE_HISTORY
          {% if not loop.last %}
            UNION ALL
        {% endif %} 
        {% elif  entity_typ == 'X'  %} 
         select
        NULL AS OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_IOS,
NULL AS creative_id,
NULL AS OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_IPAD,
NULL AS OBJECT_STORY_LINK_DATA_DESCRIPTION,
NULL AS TEMPLATE_APP_LINK_SPEC_IOS,
NULL AS TITLE,
NULL AS TEMPLATE_LINK,
NULL AS VIDEO_CALL_TO_ACTION_VALUE_LINK,
NULL AS ACTOR_ID,
NULL AS OBJECT_STORY_LINK_DATA_CAPTION,
NULL AS OBJECT_URL,
NULL AS _FIVETRAN_ID,
NULL AS EFFECTIVE_INSTAGRAM_STORY_ID,
NULL AS PAGE_MESSAGE,
NULL AS CAROUSEL_AD_LINK,
NULL AS ASSET_FEED_SPEC_LINK_URLS,
NULL AS OBJECT_STORY_ID,
NULL AS CALL_TO_ACTION_TYPE,
NULL AS USE_PAGE_ACTOR_OVERRIDE,
NULL AS IMAGE_URL,
NULL AS INSTAGRAM_PERMALINK_URL,
NULL AS creative_name,
NULL AS TEMPLATE_CHILD_ATTACHMENTS,
NULL AS PAGE_LINK,
NULL AS TEMPLATE_MESSAGE,
NULL AS TEMPLATE_APP_LINK_SPEC_IPHONE,
NULL AS TEMPLATE_PAGE_LINK,
NULL AS OBJECT_STORY_LINK_DATA_LINK,
NULL AS OBJECT_ID,
NULL AS TEMPLATE_APP_LINK_SPEC_ANDROID,
NULL AS OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_ANDROID,
NULL AS EFFECTIVE_OBJECT_STORY_ID,
NULL AS PRODUCT_SET_ID,
NULL AS IMAGE_FILE,
NULL AS BODY,
NULL AS OBJECT_STORY_LINK_DATA_APP_LINK_SPEC_IPHONE,
NULL AS STATUS,
NULL AS OBJECT_STORY_LINK_DATA_MESSAGE,
NULL AS THUMBNAIL_URL,
NULL AS TEMPLATE_DESCRIPTION,
NULL AS VIDEO_ID,
NULL AS INSTAGRAM_STORY_ID,
NULL AS OBJECT_TYPE,
NULL AS LINK_OG_ID,
NULL AS BRANDED_CONTENT_SPONSOR_PAGE_ID,
NULL AS TEMPLATE_CAPTION,
NULL AS TEMPLATE_URL,
NULL AS ACCOUNT_ID,
NULL AS IMAGE_HASH,
NULL AS LINK_URL,
NULL AS APPLINK_TREATMENT,
NULL AS TEMPLATE_APP_LINK_SPEC_IPAD,
NULL AS INSTAGRAM_ACTOR_ID,
NULL AS OBJECT_STORY_LINK_DATA_CHILD_ATTACHMENTS,
NULL AS URL_TAGS,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM dual     

    {% endif %}
{% endfor %}