
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sales_dataflo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sales_dataflo'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["ETL"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["History_Data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  sales_dataflo :
    Stage:
          materialized: table
          
    Tables:
          materialized: table      
          
# views settings
    Views:
          materialized: view
          
    ml_insights_data:
          materialized: table
          schema: ml_insights_data
                   
# seeds (reference files, loaded into tables) module settings
seeds:
  sales_dataflo:
    schema: seed

models:
 +incremental_strategy: "delete+insert"
     
vars:
  # Salesforce Schema and Table info
  V_Entity_Schema          : ENTITY_SCHEMA
  V_Schema                 : DBT_SALESDATAFLO
  V_SF_CRM_ETL             : FIVETRAN_SF 
  V_DB                     : DATAFLOTEST_DATABASE
  V_Sales                  : ENTITY_DATASOURCES
  V_Mkt                    : ENTITY_DATASOURCES


  linkedin__use_local_currency: true

  enable_SF_source : true
  
  enable_crm_warehouse :                true
  enable_finance_warehouse :            false
  enable_projects_warehouse :           false
  enable_marketing_warehouse :          false
  enable_ads_warehouse :                false
  enable_product_warehouse :            false
  enable_subscriptions_warehouse :      false
  
  ad_reporting__linkedin_ads_enabled: true
  ad_reporting__google_ads_enabled: true
  ad_reporting__facebook_ads_enabled: true


  