{% set results = get_column_values_from_query("select * from " ~ var('V_DB') ~ "." ~ var('V_Entity_Schema')~ "." ~ var('V_Mkt')~" where DATASOURCE_TYPE = 'LI_ADS' and READY_TO_PROCESS = 'TRUE'", "ENTITY_DATASORUCE_NAME||'#'||DATASOURCE_TYPE")%}

{% if not var("enable_SF_source") %}
{{
    config(
        enabled=false
    )
}}
{% endif %}

{% for V_SF_Schema in results %}


{% if V_SF_Schema != 'X' %} 
{% set schema_nm,entity_typ = V_SF_Schema.split('#') %}
{% else %}
{% set entity_typ = 'X' %}
{% endif %}

 {% if  entity_typ == 'LI_ADS'  %} 
      
  select
        {{ dbt_utils.surrogate_key('ID') }}  AS CRE_ID,
       SPONSORED_UPDATE_SHARE_CONTENT_TITLE,
SPOTLIGHT_CALL_TO_ACTION,
JOBS_LOGO,
SPONSORED_UPDATE_CAROUSEL_DIRECT_SPONSORED_CONTENT,
SPOTLIGHT_DESCRIPTION,
CALL_TO_ACTION_LABEL_TYPE,
JOBS_ORGANIZATION,
SPONSORED_VIDEO_MEDIA_ASSET,
SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_DESCRIPTION,
SPONSORED_UPDATE_CAROUSEL_SHARE_SUBJECT,
TEXT_AD_TEXT,
FOLLOW_COMPANY_ORGANIZATION_NAME,
REVIEW_STATUS,
REFERENCE,
VERSION_TAG,
SPOTLIGHT_HEADLINE,
CAMPAIGN_ID,
SPOTLIGHT_LOGO,
SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_SHARE_MEDIA_CATEGORY,
ID,
SPONSORED_UPDATE_SHARE,
SPONSORED_UPDATE_SHARE_SUBJECT,
SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST,
SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_TITLE,
SPOTLIGHT_CUSTOM_BACKGROUND,
CREATED_TIME,
SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST_VALUE_SPECIFIC_CONTENT_SHARE_CONTENT_MEDIA,
SPONSORED_UPDATE_DIRECT_SPONSORED_CONTENT,
SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_CONTENT_ENTITIES,
TYPE,
SPONSORED_UPDATE_ACTIVITY,
JOBS_COMPANY_NAME,
FOLLOW_COMPANY_ORGANIZATION_LOGO,
SPONSORED_UPDATE_CAROUSEL_SHARE,
SPONSORED_UPDATE_SHARE_CONTENT_SHARE_MEDIA_CATEGORY,
LAST_MODIFIED_TIME,
TEXT_AD_TITLE,
SPONSORED_UPDATE_CAROUSEL_ACTIVITY,
SPOTLIGHT_SHOW_MEMBER_PROFILE_PHOTO,
SPONSORED_IN_MAIL_CONTENT,
SPONSORED_UPDATE_SHARE_CONTENT_DESCRIPTION,
STATUS,
FOLLOW_COMPANY_CALL_TO_ACTION,
SPONSORED_UPDATE_SHARE_CONTENT_CONTENT_ENTITIES,
CALL_TO_ACTION_TARGET,
CLICK_URI,
SPOTLIGHT_FORUM_NAME,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM {{ schema_nm }}.CREATIVE_HISTORY
          {% if not loop.last %}
            UNION ALL
        {% endif %} 
        {% elif  entity_typ == 'X'  %} 
         select
        NULL AS SPONSORED_UPDATE_SHARE_CONTENT_TITLE,
NULL AS SPOTLIGHT_CALL_TO_ACTION,
NULL AS JOBS_LOGO,
NULL AS SPONSORED_UPDATE_CAROUSEL_DIRECT_SPONSORED_CONTENT,
NULL AS SPOTLIGHT_DESCRIPTION,
NULL AS CALL_TO_ACTION_LABEL_TYPE,
NULL AS JOBS_ORGANIZATION,
NULL AS SPONSORED_VIDEO_MEDIA_ASSET,
NULL AS SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_DESCRIPTION,
NULL AS SPONSORED_UPDATE_CAROUSEL_SHARE_SUBJECT,
NULL AS TEXT_AD_TEXT,
NULL AS FOLLOW_COMPANY_ORGANIZATION_NAME,
NULL AS REVIEW_STATUS,
NULL AS REFERENCE,
NULL AS VERSION_TAG,
NULL AS SPOTLIGHT_HEADLINE,
NULL AS CAMPAIGN_ID,
NULL AS SPOTLIGHT_LOGO,
NULL AS SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_SHARE_MEDIA_CATEGORY,
NULL AS ID,
NULL AS SPONSORED_UPDATE_SHARE,
NULL AS SPONSORED_UPDATE_SHARE_SUBJECT,
NULL AS SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST,
NULL AS SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_TITLE,
NULL AS SPOTLIGHT_CUSTOM_BACKGROUND,
NULL AS CREATED_TIME,
NULL AS SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST_VALUE_SPECIFIC_CONTENT_SHARE_CONTENT_MEDIA,
NULL AS SPONSORED_UPDATE_DIRECT_SPONSORED_CONTENT,
NULL AS SPONSORED_UPDATE_CAROUSEL_SHARE_CONTENT_CONTENT_ENTITIES,
NULL AS TYPE,
NULL AS SPONSORED_UPDATE_ACTIVITY,
NULL AS JOBS_COMPANY_NAME,
NULL AS FOLLOW_COMPANY_ORGANIZATION_LOGO,
NULL AS SPONSORED_UPDATE_CAROUSEL_SHARE,
NULL AS SPONSORED_UPDATE_SHARE_CONTENT_SHARE_MEDIA_CATEGORY,
NULL AS LAST_MODIFIED_TIME,
NULL AS TEXT_AD_TITLE,
NULL AS SPONSORED_UPDATE_CAROUSEL_ACTIVITY,
NULL AS SPOTLIGHT_SHOW_MEMBER_PROFILE_PHOTO,
NULL AS SPONSORED_IN_MAIL_CONTENT,
NULL AS SPONSORED_UPDATE_SHARE_CONTENT_DESCRIPTION,
NULL AS STATUS,
NULL AS FOLLOW_COMPANY_CALL_TO_ACTION,
NULL AS SPONSORED_UPDATE_SHARE_CONTENT_CONTENT_ENTITIES,
NULL AS CALL_TO_ACTION_TARGET,
NULL AS CLICK_URI,
NULL AS SPOTLIGHT_FORUM_NAME,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM dual     

    {% endif %}
{% endfor %}