{% set results = get_column_values_from_query("select * from " ~ var('V_DB') ~ "." ~ var('V_Entity_Schema')~ "." ~ var('V_Mkt')~" where DATASOURCE_TYPE = 'GA_ADS' and READY_TO_PROCESS = 'TRUE'", "ENTITY_DATASORUCE_NAME||'#'||DATASOURCE_TYPE")%}

{% if not var("enable_SF_source") %}
{{
    config(
        enabled=false
    )
}}
{% endif %}

{% for V_SF_Schema in results %}


{% if V_SF_Schema != 'X' %} 
{% set schema_nm,entity_typ = V_SF_Schema.split('#') %}
{% else %}
{% set entity_typ = 'X' %}
{% endif %}

 {% if  entity_typ == 'GA_ADS'  %} 
      
  select
        {{ dbt_utils.surrogate_key('ID') }}  AS CCH_ID,
       CARRIER_COUNTRY_CODE,
PROXIMITY_ADDRESS_STREET_ADDRESS_2,
MOBILE_APP_CATEGORY_ID,
AD_SCHEDULE_START_MINUTE,
OPERATING_SYSTEM_NAME,
MOBILE_DEVICE_MANUFACTURER_NAME,
USER_LIST_ELIGIBLE_FOR_SEARCH,
MOBILE_APPLICATION_APP_ID,
PROXIMITY_GEO_POINT_LATITUDE_IN_MICRO_DEGREES,
YOUTUBE_VIDEO_ID,
PARENT_TYPE,
USER_LIST_ID,
GENDER_TYPE,
MOBILE_APPLICATION_DISPLAY_NAME,
YOUTUBE_VIDEO_NAME,
VERTICAL_PATH,
PLATFORM_NAME,
KEYWORD_TEXT,
PROXIMITY_RADIUS_DISTANCE_UNITS,
PROXIMITY_CITY_NAME,
PROXIMITY_RADIUS_IN_UNITS,
PLACEMENT_URL,
VERTICAL_ID,
LANGUAGE_CODE,
YOUTUBE_CHANNEL_NAME,
_FIVETRAN_SYNCED,
MOBILE_DEVICE_OPERATING_SYSTEM_NAME,
LOCATION_TARGETING_STATUS,
CAMPAIGN_CRITERION_STATUS,
USER_INTEREST_ID,
INCOME_RANGE_TYPE,
USER_INTEREST_PARENT_ID,
PROXIMITY_COUNTRY_CODE,
KEYWORD_MATCH_TYPE,
PROXIMITY_POSTAL_CODE,
MOBILE_DEVICE_NAME,
YOUTUBE_CHANNEL_ID,
USER_INTEREST_NAME,
MOBILE_DEVICE_TYPE,
VERTICAL_PARENT_ID,
LANGUAGE_NAME,
AD_SCHEDULE_END_MINUTE,
IS_NEGATIVE,
AGE_RANGE_TYPE,
CONTENT_LABEL_TYPE,
OPERATING_SYSTEM_OPERATOR_TYPE,
PROXIMITY_ADDRESS_STREET_ADDRESS,
OPERATING_SYSTEM_OS_MAJOR_VERSION,
AD_SCHEDULE_END_HOUR,
CAMPAIGN_CRITERION_TYPE,
CARRIER_NAME,
BASE_CAMPAIGN_ID,
AD_SCHEDULE_START_HOUR,
UPDATED_AT,
BID_MODIFIER,
CRITERION_TYPE,
PROXIMITY_PROVINCE_NAME,
OPERATING_SYSTEM_OS_MINOR_VERSION,
USER_LIST_ELIGIBLE_FOR_DISPLAY,
LOCATION_DISPLAY_TYPE,
AD_SCHEDULE_DAY_OF_WEEK,
ID,
LOCATION_PARENT_LOCATIONS,
IP_BLOCK_IP_ADDRESS,
LOCATION_NAME,
PROXIMITY_GEO_POINT_LONGITUDE_IN_MICRO_DEGREES,
USER_LIST_MEMBERSHIP_STATUS,
USER_LIST_NAME,
PROXIMITY_PROVINCE_CODE,
CAMPAIGN_ID,
MOBILE_APP_DISPLAY_NAME,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM {{ schema_nm }}.CAMPAIGN_CRITERION_HISTORY
          {% if not loop.last %}
            UNION ALL
        {% endif %} 
        {% elif  entity_typ == 'X'  %} 
         select
        Null As CARRIER_COUNTRY_CODE,
Null As PROXIMITY_ADDRESS_STREET_ADDRESS_2,
Null As MOBILE_APP_CATEGORY_ID,
Null As AD_SCHEDULE_START_MINUTE,
Null As OPERATING_SYSTEM_NAME,
Null As MOBILE_DEVICE_MANUFACTURER_NAME,
Null As USER_LIST_ELIGIBLE_FOR_SEARCH,
Null As MOBILE_APPLICATION_APP_ID,
Null As PROXIMITY_GEO_POINT_LATITUDE_IN_MICRO_DEGREES,
Null As YOUTUBE_VIDEO_ID,
Null As PARENT_TYPE,
Null As USER_LIST_ID,
Null As GENDER_TYPE,
Null As MOBILE_APPLICATION_DISPLAY_NAME,
Null As YOUTUBE_VIDEO_NAME,
Null As VERTICAL_PATH,
Null As PLATFORM_NAME,
Null As KEYWORD_TEXT,
Null As PROXIMITY_RADIUS_DISTANCE_UNITS,
Null As PROXIMITY_CITY_NAME,
Null As PROXIMITY_RADIUS_IN_UNITS,
Null As PLACEMENT_URL,
Null As VERTICAL_ID,
Null As LANGUAGE_CODE,
Null As YOUTUBE_CHANNEL_NAME,
Null As _FIVETRAN_SYNCED,
Null As MOBILE_DEVICE_OPERATING_SYSTEM_NAME,
Null As LOCATION_TARGETING_STATUS,
Null As CAMPAIGN_CRITERION_STATUS,
Null As USER_INTEREST_ID,
Null As INCOME_RANGE_TYPE,
Null As USER_INTEREST_PARENT_ID,
Null As PROXIMITY_COUNTRY_CODE,
Null As KEYWORD_MATCH_TYPE,
Null As PROXIMITY_POSTAL_CODE,
Null As MOBILE_DEVICE_NAME,
Null As YOUTUBE_CHANNEL_ID,
Null As USER_INTEREST_NAME,
Null As MOBILE_DEVICE_TYPE,
Null As VERTICAL_PARENT_ID,
Null As LANGUAGE_NAME,
Null As AD_SCHEDULE_END_MINUTE,
Null As IS_NEGATIVE,
Null As AGE_RANGE_TYPE,
Null As CONTENT_LABEL_TYPE,
Null As OPERATING_SYSTEM_OPERATOR_TYPE,
Null As PROXIMITY_ADDRESS_STREET_ADDRESS,
Null As OPERATING_SYSTEM_OS_MAJOR_VERSION,
Null As AD_SCHEDULE_END_HOUR,
Null As CAMPAIGN_CRITERION_TYPE,
Null As CARRIER_NAME,
Null As BASE_CAMPAIGN_ID,
Null As AD_SCHEDULE_START_HOUR,
Null As UPDATED_AT,
Null As BID_MODIFIER,
Null As CRITERION_TYPE,
Null As PROXIMITY_PROVINCE_NAME,
Null As OPERATING_SYSTEM_OS_MINOR_VERSION,
Null As USER_LIST_ELIGIBLE_FOR_DISPLAY,
Null As LOCATION_DISPLAY_TYPE,
Null As AD_SCHEDULE_DAY_OF_WEEK,
Null As ID,
Null As LOCATION_PARENT_LOCATIONS,
Null As IP_BLOCK_IP_ADDRESS,
Null As LOCATION_NAME,
Null As PROXIMITY_GEO_POINT_LONGITUDE_IN_MICRO_DEGREES,
Null As USER_LIST_MEMBERSHIP_STATUS,
Null As USER_LIST_NAME,
Null As PROXIMITY_PROVINCE_CODE,
Null As CAMPAIGN_ID,
Null As MOBILE_APP_DISPLAY_NAME,

        '{{ schema_nm }}' as Source_type,
        'D_BASIC_AD_ACTIONS_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS 
    FROM dual     

    {% endif %}
{% endfor %}