{% set results = get_column_values_from_query("select * from " ~ var('V_DB') ~ "." ~ var('V_Schema')~ ".DIM_SALES_ENTITY where ENTITY_TYPE = 'HS'", 'ENTITY_NAME')%}

{% if not var("enable_SF_source") %}
{{
    config(
        enabled=false
    )
}}
{% endif %}

{{
    config(
        materialized='incremental',
        unique_key= 'DEAL_ID'
      )
}}

{% for V_SF_Schema in results %}
 {% if  V_SF_Schema[0:2] == 'HS'  %}    
  select
        {{ dbt_utils.surrogate_key('DEAL_ID') }}  AS DEAL_ID,
        DEAL_ID as Source_DEAL_ID,
        PORTAL_ID,
        IS_DELETED,
        _FIVETRAN_SYNCED,
        PROPERTY_HS_DEAL_STAGE_PROBABILITY,
        PROPERTY_HS_CLOSED_AMOUNT_IN_HOME_CURRENCY,
        PROPERTY_HS_LASTMODIFIEDDATE,
        PROPERTY_HS_CLOSED_AMOUNT,
        PROPERTY_HS_TIME_IN_APPOINTMENTSCHEDULED,
        PROPERTY_HS_IS_CLOSED,
        PROPERTY_HS_CREATED_BY_USER_ID,
        PROPERTY_DAYS_TO_CLOSE,
        PROPERTY_HS_DATE_ENTERED_APPOINTMENTSCHEDULED,
        PROPERTY_HS_PROJECTED_AMOUNT,
        PROPERTY_HS_PROJECTED_AMOUNT_IN_HOME_CURRENCY,
        PROPERTY_AMOUNT_IN_HOME_CURRENCY,
        PROPERTY_HS_DATE_EXITED_DECISIONMAKERBOUGHTIN,
        PROPERTY_HS_DATE_ENTERED_DECISIONMAKERBOUGHTIN,
        PROPERTY_HS_DATE_EXITED_CONTRACTSENT,
        PROPERTY_HS_DATE_EXITED_APPOINTMENTSCHEDULED,
        PROPERTY_HS_DATE_ENTERED_PRESENTATIONSCHEDULED,
        PROPERTY_HS_TIME_IN_QUALIFIEDTOBUY,
        PROPERTY_HS_TIME_IN_CLOSEDWON,
        PROPERTY_HS_TIME_IN_DECISIONMAKERBOUGHTIN,
        PROPERTY_HS_DATE_EXITED_PRESENTATIONSCHEDULED,
        PROPERTY_HS_DATE_ENTERED_QUALIFIEDTOBUY,
        PROPERTY_HS_DATE_EXITED_QUALIFIEDTOBUY,
        PROPERTY_HS_DATE_ENTERED_CONTRACTSENT,
        PROPERTY_HS_TIME_IN_PRESENTATIONSCHEDULED,
        PROPERTY_HS_DATE_ENTERED_CLOSEDWON,
        PROPERTY_HS_TIME_IN_CONTRACTSENT,
        PROPERTY_HS_NEXT_STEP,
        PROPERTY_HS_MANUAL_FORECAST_CATEGORY,
        PROPERTY_DEALNAME,
        PROPERTY_CLOSEDATE,
        PROPERTY_CREATEDATE,
        DEAL_PIPELINE_STAGE_ID,
        OWNER_ID,
        PROPERTY_HS_UPDATED_BY_USER_ID,
        PROPERTY_HS_CREATEDATE,
        PROPERTY_HS_USER_IDS_OF_ALL_OWNERS,
        PROPERTY_HS_ALL_OWNER_IDS,
        DEAL_PIPELINE_ID,
        PROPERTY_HUBSPOT_OWNER_ASSIGNEDDATE,
        PROPERTY_PRODUCT_OF_INTEREST,
        PROPERTY_AMOUNT,
        PROPERTY_POINT_OF_CONTACT,
        PROPERTY_DEALTYPE,   
        '{{ V_SF_Schema }}' as Source_type,
        'D_DEAL_STG_LOAD' AS DW_SESSION_NM,
        {{ dbt_utils.current_timestamp() }} AS DW_INS_UPD_DTS    
    FROM {{ V_SF_Schema }}.Deal
    {% if not loop.last %}
            UNION ALL
        {% endif %}
    {% endif %}
{% endfor %}

